[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.111.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.111.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

#
# Redireccions del cas català
#
[[redirects]]
from = "/ca/:year/:month/:slug"
to = "/ca/posts/:year/:slug"
status = 301

#
# Redireccions del cas anglès
#
[[redirects]]
from = "/tags/*"
to = "/en/tags/:splat"
status = 301

[[redirects]]
from = "/categories/*"
to = "/en/categories/:splat"
status = 301

[[redirects]]
from = "/archives/*"
to = "/en/archives/:splat"
status = 301

[[redirects]]
# captura '/page/2' paginats de la pagina principal
# captura '/page/contact' pàgines ordinàries
from = "/page/*"
to = "/en/page/:splat"
status = 301

[[redirects]]
# elimina el mes dels posts
# afegeix el 'posts' a URL
from = "/:year/:month/:slug"
to = "/en/posts/:year/:slug"
status = 301

