#!/bin/bash

DIM=1024

mogrify -filter Triangle \
        -define filter:support=2 \
        -auto-orient \
        -thumbnail $DIM \
        -unsharp 0.25x0.08+8.3+0.045 \
        -dither None -posterize 136 -quality 82 \
        -define jpeg:fancy-upsampling=off \
        -define png:compression-filter=5 \
        -define png:compression-level=9 \
        -define png:compression-strategy=1 \
        -define png:exclude-chunk=all \
        -interlace none \
        -colorspace sRGB $1

# reduce pp/*.png
